---
title: "01-Упражнение"
subtitle: "Домашна работа"
author: "ас.д-р Костадин Костадинов"
language: custom.yml
format:
  pdf:
    mainfont: "Old Standard TT"
    sansfont: "Old Standard TT"
    monofont: "Old Standard TT"
    colorlinks: true
---
# Домашна работа

1.  Да се определи възрастовата структура на преминалите болни през Болница Х като разполагате с данни по възрастови групи (екстензивен показател).

+--------------------------+---------+---------+---------+-----------+---------+
| Възраст                  | 0-1г.   | 1-4г.   | 5-9г.   | 10-19г.   | Общо    |
+:=========================+:========+:========+:========+:==========+:========+
| Болни с Хепатит А        | 70      | 41      | 102     | 87        | 300     |
+--------------------------+---------+---------+---------+-----------+---------+
| Възрастова структура (%) |         |         |         |           |         |
+--------------------------+---------+---------+---------+-----------+---------+

2.  Да се изчислят стандартизираните показатели за плодовитостта в районите А и Б. За стандарт да се приеме възрастовият състав на жените от район Б. Да се анализират получените резултати.

|         | Район А |            | Район Б |            |
|---------|---------|------------|---------|------------|
| Възраст | Жени    | Живородени | Жени    | Живородени |
| 15-19   | 1 000   | 18         | 1 200   | 22         |
| 21-30   | 9 000   | 225        | 7 000   | 175        |
| 31-49   | 8 000   | 128        | 10 000  | 160        |
| Всичко  | 18 000  | 371        | 18200   | 357        |

3.  Да се изчислят стандартизираните показатели за леталитета в две градски болници - Болница А и Болница Б. За стандарт да се приеме съставът на болните в болница Б. Да се анализират получените резултати.

+---------------------+------------+------------+------------+------------+
| Болест              | Преминали  | Починали   | Преминали  | Починали   |
|                     |            |            |            |            |
|                     | (А)        | (А)        | (Б)        | (А)        |
+=====================+============+============+============+============+
| Хипертонична болест | 180        | 4          | 200        | 4          |
+---------------------+------------+------------+------------+------------+
| Рак на стомаха      | 100        | 30         | 90         | 27         |
+---------------------+------------+------------+------------+------------+
| Инфаркт на миокарда | 120        | 8          | 160        | 10         |
+---------------------+------------+------------+------------+------------+
| Всичко              | 400        | 42         | 450        | 41         |
+---------------------+------------+------------+------------+------------+