---
title: "03-Домашна работа"
subtitle: "T- тест"
author: "ас.д-р Костадин Костадинов"
language: custom.yml
format:
  pdf:
    mainfont: "Old Standard TT"
    sansfont: "Old Standard TT"
    monofont: "Old Standard TT"
    colorlinks: true
---

```{r}
#| include: false
#| warning: false
#knitr::opts_chunk$set(dev = "cairo_pdf")
#| include: false
#| warning: false
library(ggthemes)
library(gt)
library(gtsummary)
library(showtext)
library(ggeffects)
library(patchwork)
library(scales)
library(sysfonts)
library(ggsci)
library(ggridges)
library(rstatix)
library(statsExpressions)
library(tidyverse)
library(broom)
library(showtext)
library(janitor)
ggplot2::theme_set(
  ggthemes::theme_tufte(
    base_size = 10,
    base_family = "Cormorant Infant",
    ticks = FALSE))
sysfonts::font_add(family = "Cormorant Infant", regular = "CormorantInfant-Regular.ttf")
showtext_auto()
```

# Задача 1.

По случаен начин са подбрани две извадки с обем съответно n = 248 и n2 = 140 индивида с кардиологични проблеми. В таблиците е регистриран пулсът на пациентите. Изчислете границите на 95% доверителен интервал за средните величини на популацията за двете извадки. Докажете дали средната аритметична е статистически различна спрямо двете групи пациенти, използвайки Т-тест.

+----------------+-------------------+----------------+-------------------+
| Група 1 - пулс | Група 1 - честота | Група 2 - пулс | Група 2 - честота |
+================+===================+================+===================+
| 60             | 4                 | 80             | 10                |
+----------------+-------------------+----------------+-------------------+
| 65             | 18                | 85             | 15                |
+----------------+-------------------+----------------+-------------------+
| 70             | 25                | 90             | 25                |
+----------------+-------------------+----------------+-------------------+
| 75             | 30                | 95             | 30                |
+----------------+-------------------+----------------+-------------------+
| 80             | 50                | 100            | 28                |
+----------------+-------------------+----------------+-------------------+
| 85             | 48                | 105            | 16                |
+----------------+-------------------+----------------+-------------------+
| 90             | 36                | 120            | 2                 |
+----------------+-------------------+----------------+-------------------+
| 95             | 28                | 125            | 8                 |
+----------------+-------------------+----------------+-------------------+
| 100            | 9                 | 130            | 6                 |
+----------------+-------------------+----------------+-------------------+
| Общо           | 248               | Общо           | 140               |
+----------------+-------------------+----------------+-------------------+

\newpage

# Задача 2.

Да се определи съществено ли е различието във виталния капацитет при индивиди от мъжки пол на 19 годишна възраст две независими извадки с еднакъв брой случаи. В едната извадка са включени баскетболисти, а в другата младежи. трениращи плувен спорт. Тестът да се извърши чрез t теста, като необходимите статистически параметри - средна аритметична и стандартно отклонение да се изчислят както при групирани данни

+-------------------+---------+-------------------+---------+
| Витален капацитет | Честота | Витален капацитет | Честота |
|                   |         |                   |         |
| баскетболисти     |         | Плувци            |         |
+===================+=========+===================+=========+
| 2601-2800         | 12      | 3401-3600         | 13      |
+-------------------+---------+-------------------+---------+
| 2801-3000         | 21      | 3601-3800         | 26      |
+-------------------+---------+-------------------+---------+
| 3001-3200         | 35      | 3801-4000         | 35      |
+-------------------+---------+-------------------+---------+
| 3201-3400         | 62      | 4001-4200         | 58      |
+-------------------+---------+-------------------+---------+
| 3401-3600         | 33      | 4201-4400         | 30      |
+-------------------+---------+-------------------+---------+
| 3601-3800         | 19      | 4401-4600         | 20      |
+-------------------+---------+-------------------+---------+
| 3801-4000         | 15      | 4601-4800         | 15      |
+-------------------+---------+-------------------+---------+
| общо:             | 197     | общо:             | 197     |
+-------------------+---------+-------------------+---------+
