---
title: "02-Домашна работа"
subtitle: "Дискриптивна и инферетна статистика"
author: "ас.д-р Костадин Костадинов"
language: 
      tag: '!expr'
      value: system('lang_yaml custom.yml')
format:
  pdf:
    mainfont: "Old Standard TT"
    sansfont: "Old Standard TT"
    monofont: "Old Standard TT"
    colorlinks: true
---

```{r}
#| include: false
#| warning: false
#knitr::opts_chunk$set(dev = "cairo_pdf")
#| include: false
#| warning: false
library(ggthemes)
library(gt)
library(gtsummary)
library(showtext)
library(ggeffects)
library(patchwork)
library(scales)
library(sysfonts)
library(ggsci)
library(ggridges)
library(rstatix)
library(statsExpressions)
library(tidyverse)
library(broom)
library(showtext)
library(janitor)
ggplot2::theme_set(
  ggthemes::theme_tufte(
    base_size = 10,
    base_family = "Cormorant Infant",
    ticks = FALSE))
sysfonts::font_add(family = "Cormorant Infant", regular = "CormorantInfant-Regular.ttf")
showtext_auto()
```

# Задача 1.

След провеждане на тренировъчен режим с група спортисти в края на периода е измерено теглото в килограми на всеки от спортистите. Получени са следните стойности: 64, 76, 68, 84, 80. 72, 74, 72 кг. Да се определи средното тегло на групата и границите на 95% од интервал на доверителност за средното тегло на спортистите в популацията.

# Задача 2.

Изследвана е съобразителността на 40 студента при работа с компютри по определена психологична задача. Да се изчисли средното време, употребено от студентите за решаването и при следните резултати. Да се определят границите на 95% - овия доверителен интервал за средната аритметична. Времето е количествена прменлива.

| Употребено време (мин) | Брой студенти |
|------------------------|---------------|
| 3                      | 1             |
| 4                      | 3             |
| 5                      | 4             |
| 6                      | 7             |
| 7                      | 8             |
| 8                      | 9             |
| 9                      | 8             |
| общо                   | 40            |


# Задача 4

Дадена е променливата "диагноза" с нейните разновидности. Преобразувайте категорийната променлива в дихотомна и изчислете границите на 95%-овия интервал на доверителност за относителния дял на пациенти с хепатит от популацията.

| Диагноза  | Брой пациенти |
|-----------|---------------|
| Колит     | 10            |
| Гастрит   | 18            |
| Апендицит | 22            |
| Язва      | 29            |
| Хепатит   | 38            |
| Общо      | 117           |

# Задача 5
По случаен принцип са подбрани две извадки с обем съответно п = 320 и n = 540 индивиди с белодробни проблеми. Изследваните случаи от първата извадка са третирани с антибактериален препарат "А" без витамини, докато в терапията на втората извадка са включени и витамини към препарата. Случаите с подобрение в първата група са 98, а във втората група 231. Да се изчислят границите на 95% в доверителен интервал за относителния дял на случаите с подобрение в двете извадки.

| Терапия         | Всички пациенти | Слуачи с подобрение |
|-----------------|-----------------|---------------------|
| А без витамини  | 320             | 98                  |
| А с витамини    | 540             | 231                 |
